USE [master]
GO
/****** Object:  Database [Tasksdb]    Script Date: 21/08/2024 15:11:02 ******/
CREATE DATABASE [Tasksdb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Tasksdb', FILENAME = N'/var/opt/mssql/data/Tasksdb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Tasksdb_log', FILENAME = N'/var/opt/mssql/data/Tasksdb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [Tasksdb] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Tasksdb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Tasksdb] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Tasksdb] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Tasksdb] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Tasksdb] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Tasksdb] SET ARITHABORT OFF 
GO
ALTER DATABASE [Tasksdb] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Tasksdb] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Tasksdb] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Tasksdb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Tasksdb] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Tasksdb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Tasksdb] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Tasksdb] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Tasksdb] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Tasksdb] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Tasksdb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Tasksdb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Tasksdb] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Tasksdb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Tasksdb] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Tasksdb] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Tasksdb] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Tasksdb] SET RECOVERY FULL 
GO
ALTER DATABASE [Tasksdb] SET  MULTI_USER 
GO
ALTER DATABASE [Tasksdb] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Tasksdb] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Tasksdb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Tasksdb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Tasksdb] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Tasksdb] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'Tasksdb', N'ON'
GO
ALTER DATABASE [Tasksdb] SET QUERY_STORE = ON
GO
ALTER DATABASE [Tasksdb] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [Tasksdb]
GO
/****** Object:  Table [dbo].[Tasks]    Script Date: 21/08/2024 15:11:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tasks](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Description] [text] NULL,
	[DateCreated] [datetime] NULL,
	[DateUpdated] [datetime] NULL,
	[status] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [Tasksdb] SET  READ_WRITE 
GO
